services:
  banking-database:
    image: 'postgres:latest'
    container_name: 'banking-db'
    restart: always
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

